# Generated by Eclipse GCJ Builder
# http://gcjbuilder.sf.net

#global targets
ALL:	main 
all:	main 

#gcj variable
GCJ=gcj  $(OPTLEVEL) $(DEBUGLEVEL) $(COMPILER_OPTIONS)

#binary output folder
BINOUT= release

#compiler options
COMPILER_OPTIONS= 

#linker options
LINKER_OPTIONS=

#object list
OBJ=src/Encrypter.o 

#custom objects
CUSTOM_OBJ=

#jar objects
CPOBJ=

#jar so
CPSO=

#project classpath 
CP="--classpath=./src/;"

#main class (or so output)
MAINCLASS=--main=Encrypter

#binary name (exe or so)
BIN=$(BINOUT)/Vic_Cipher_Encrypter

#library path list
LIBRARYPATH=-L$(BINOUT) 

#libraries (so) list
LIBRARIES=

#resource objects list
RESOB=

#compiler optimization level
OPTLEVEL= -O3

#compiler debug level
DEBUGLEVEL= -g0


#object targets
%.o:	%.java
	$(GCJ) $(CP)  -c $? -o $@
	
##################
#dummy targets (depend on config)

#classpath objects target


#classpath so target


#resource objects target



#################

	
#main target

main: setup $(CPOBJ) $(RESOB) $(OBJ) $(CPSO)
	$(GCJ) $(LINKER_OPTIONS) $(MAINCLASS) $(CPOBJ) $(CUSTOM_OBJ) $(RESOB) $(OBJ) -o$(BIN)   $(LIBRARYPATH) $(LIBRARIES) $(CPSO)

#setup output folders
setup:
	mkdir -p $(BINOUT)/resource

#clean target    
clean:
	rm -f `find . -name "*.o"`
	rm -r $(BINOUT)

